In [6]:
import pandas as pd
import ast #convierte los strings del csv a listas de python

from rich.jupyter import display

#Se llama el Corpus con las columnas de etiqueta
df = pd.read_csv("../data/processed/resenas_pos_tagged.csv")

df["tokens_spacy"] = df["tokens_spacy"].apply(ast.literal_eval)
df["tokens_nltk"] = df["tokens_nltk"].apply(ast.literal_eval)

df.head(5)

,reseña,calificación,tipo_lugar,fuente,nombre,fecha,grupo_de_viaje,mes,tokens_spacy,tokens_nltk
0,fue una pésima experiencia llegamos solo por u...,1,hotel,https://search.google.com/local/reviews?placei...,baldi hot springs hotel resort & spa,23/05/2026,NaN,mayo,"[(fue, AUX), (una, DET), (pésima, ADJ), (exper...","[(fue, NN), (una, JJ), (pésima, NN), (experien..."
1,todo muy bonito realmente me quedo sin palabra...,5,hotel,https://search.google.com/local/reviews?placei...,baldi hot springs hotel resort & spa,17/05/2026,NaN,mayo,"[(todo, PRON), (muy, ADV), (bonito, ADJ), (rea...","[(todo, NN), (muy, NN), (bonito, NN), (realmen..."
2,una experiencia relajante e imperdible en cost...,5,hotel,https://search.google.com/local/reviews?placei...,baldi hot springs hotel resort & spa,16/05/2026,familia,mayo,"[(una, DET), (experiencia, NOUN), (relajante, ...","[(una, JJ), (experiencia, NN), (relajante, NN)..."
3,buena experiencia nos habían recomendado en gr...,4,hotel,https://search.google.com/local/reviews?placei...,baldi hot springs hotel resort & spa,16/05/2026,pareja,mayo,"[(buena, ADJ), (experiencia, NOUN), (nos, PRON...","[(buena, NN), (experiencia, NN), (nos, JJ), (h..."
4,un gran lugar para hospedarse un pasasar un ra...,5,hotel,https://search.google.com/local/reviews?placei...,baldi hot springs hotel resort & spa,15/05/2026,familia,mayo,"[(un, DET), (gran, ADJ), (lugar, NOUN), (para,...","[(un, JJ), (gran, NN), (lugar, NN), (para, NN)..."

In [10]:
from src.analysis.metrics import calculo_densidad_lex,calculo_radio
from src.analysis.pos_analyzer import distribucion_pos
from IPython.display import display

#Se aplican las funciones de metrics creadas
df["radio"] = df["tokens_spacy"].apply(calculo_radio)
df["densidad_lexica"] = df["tokens_spacy"].apply(calculo_densidad_lex)

#Se aplica la funcion creada en el pos_analyzer
df_rest = distribucion_pos(df["tokens_spacy"])
print("Distribución de las etiquetas: ")
display(df_rest)

Distribución de las etiquetas:

   Categoría  Frecuencia  Porcentaje
0       NOUN        6775       22.91
1        DET        4188       14.16
2        ADP        3579       12.10
3        ADJ        3559       12.04
4       VERB        3075       10.40
5        ADV        2138        7.23
6       PRON        1757        5.94
7        AUX        1538        5.20
8      CCONJ        1451        4.91
9      SCONJ         702        2.37
10     PROPN         440        1.49
11       NUM         350        1.18
12      PART          10        0.03
13      INTJ           8        0.03