In [1]:
import pandas as pd
import ast #convierte los strings del csv a listas de python

from rich.jupyter import display

#Se llama el Corpus con las columnas de etiqueta
ruta = "../data/processed/resenas_pos_tagged.csv"
df = pd.read_csv("../data/processed/resenas_pos_tagged.csv")

df["tokens_spacy"] = df["tokens_spacy"].apply(ast.literal_eval)
df["tokens_nltk"] = df["tokens_nltk"].apply(ast.literal_eval)

df.head(5)

,reseña,calificación,tipo_lugar,fuente,nombre,fecha,grupo_de_viaje,mes,tokens_spacy,tokens_nltk
0,fue una pésima experiencia llegamos solo por u...,1,hotel,https://search.google.com/local/reviews?placei...,baldi hot springs hotel resort & spa,23/05/2026,NaN,mayo,"[(fue, ser), (una, uno), (pésima, pésimo), (ex...","[(fue, NN), (una, JJ), (pésima, NN), (experien..."
1,todo muy bonito realmente me quedo sin palabra...,5,hotel,https://search.google.com/local/reviews?placei...,baldi hot springs hotel resort & spa,17/05/2026,NaN,mayo,"[(todo, todo), (muy, mucho), (bonito, bonito),...","[(todo, NN), (muy, NN), (bonito, NN), (realmen..."
2,una experiencia relajante e imperdible en cost...,5,hotel,https://search.google.com/local/reviews?placei...,baldi hot springs hotel resort & spa,16/05/2026,familia,mayo,"[(una, uno), (experiencia, experiencia), (rela...","[(una, JJ), (experiencia, NN), (relajante, NN)..."
3,buena experiencia nos habían recomendado en gr...,4,hotel,https://search.google.com/local/reviews?placei...,baldi hot springs hotel resort & spa,16/05/2026,pareja,mayo,"[(buena, buen), (experiencia, experiencia), (n...","[(buena, NN), (experiencia, NN), (nos, JJ), (h..."
4,un gran lugar para hospedarse un pasasar un ra...,5,hotel,https://search.google.com/local/reviews?placei...,baldi hot springs hotel resort & spa,15/05/2026,familia,mayo,"[(un, uno), (gran, gran), (lugar, lugar), (par...","[(un, JJ), (gran, NN), (lugar, NN), (para, NN)..."

In [4]:
from src.analysis.metrics import calculo_densidad_lex,calculo_radio
from src.analysis.pos_analyzer import distribucion_pos

#Se aplican las funciones de metrics creadas
df["radio"] = df["tokens_spacy"].apply(calculo_radio)
df["densidad_lexica"] = df["tokens_spacy"].apply(calculo_densidad_lex)

print("Realizando calculo de la distribucion completa...")
#Se aplica la funcion creada en el pos_analyzer
df_rest = distribucion_pos(df["tokens_spacy"])
print("Distribución de las etiquetas: ", display(df_rest))

Realizando calculo de la distribucion completa...

        Categoría  Frecuencia  Porcentaje
0              EL        2573        8.70
1               Y        1188        4.02
2              DE        1156        3.91
3             SER         883        2.99
4             UNO         853        2.88
...           ...         ...         ...
3521    ANTICIPAR           1        0.00
3522     CONTENER           1        0.00
3523       LÁCTEO           1        0.00
3524  CÓMODAMENTE           1        0.00
3525        PRICE           1        0.00

[3526 rows x 3 columns]

Distribución de las etiquetas:  None